### PR TITLE
Upgrade youtube package to fix 403 errors

### LINKED ISSUE #1364: [download fail]: Youtube
**Website name**: youtube

**OS:**: Windows

**Video URL:**: [url](https://www.youtube.com/watch?v=z7NrcTD0lb8)

**erorr message**:

```
Downloading https://www.youtube.com/watch?v=z7NrcTD0lb8 error:
https://rr4---sn-oguesn6y.googlevideo.com/videoplayback?bui=AbKP-1PuVmOLD5jWMHzBnUa65VOs7YTRMETIQloGLcbIf5xo_QhrZ9uLNHaUkTnSkF_usQiQ4aEQOhvp&c=WEB&clen=3022885&dur=186.734&ei=IlxsZvXOLcGg1d8Prc6q4AE&expire=1718399106&fvip=2&gir=yes&id=o-ACS08s2S39td3jnZUyIJWVakrjT402g5iIzJXPcQYdUW&initcwndbps=2026250&ip=2a12%3Aa301%3A1000%3A%3A20f3&itag=140&keepalive=yes&lmt=1717546166363942&lsig=AHlkHjAwRQIhAIvBKLUv3wbmsUhUvF79FTJbY0UW_fLTLiVX3SP_uFgbAiALYrtbaxCBhMbNwHikMfid7y1_ocfeVhydNwZRYW1vtg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=Sw&mime=audio%2Fmp4&mm=31%2C26&mn=sn-oguesn6y%2Csn-npoeenek&ms=au%2Conr&mt=1718376796&mv=m&mvi=4&n=yUwGoeDrj8vNMsv0&ns=ABQXMSM5nzfZgLDc1JVghVcQ&pl=32&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRgIhAJZlEsR43Pz6IEzUSEVJ9TXcWpqDwOr6IDp2MX3-t68XAiEA-zJJGebZkp6sF48WksZRO0Eb7PZ94AJ--2PF1ZwOcTk%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=UWF9fySpAdxbjdklvS-cRjLncMdq0Cx8fHDawBWA3dCmoor2shr7Y9tE2bBa&svpuc=1&txp=5432434&vprv=1&xpc=EgVo2aDSNQ%3D%3D request error: HTTP 403
github.com/iawia002/lux/request.Request
        /home/runner/work/lux/lux/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        /home/runner/work/lux/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        /home/runner/work/lux/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download
        /home/runner/work/lux/lux/downloader/downloader.go:641
github.com/iawia002/lux/app.download
        /home/runner/work/lux/lux/app/app.go:331
github.com/iawia002/lux/app.New.func1
        /home/runner/work/lux/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /home/runner/work/lux/lux/main.go:13
runtime.main
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/proc.go:271
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695
github.com/iawia002/lux/request.Request
        /home/runner/work/lux/lux/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        /home/runner/work/lux/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        /home/runner/work/lux/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download
        /home/runner/work/lux/lux/downloader/downloader.go:641
github.com/iawia002/lux/app.download
        /home/runner/work/lux/lux/app/app.go:331
github.com/iawia002/lux/app.New.func1
        /home/runner/work/lux/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /home/runner/work/lux/lux/main.go:13
runtime.main
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/proc.go:271
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695
```

**Screenshots**

Screenshot 2024-06-14 231258

**Additional context**

Looks like they changed something.
Maybe is the signature decoding function.
request error :  HTTP 403

### PR DESCRIPTION
**Pull request by gouarfig**
Upgrade youtube package to fix 403 errors

Fixes #1364, #1359, and probably plenty others not written in English 😆 

---

### Current version

```
% lux "https://www.youtube.com/watch?v=yE5Tpp2BSGw"

 Site:      YouTube youtube.com
 Title:     19. Rob Pike - What We Got Right, What We Got Wrong | GopherConAU 2023
 Type:      video
 Stream:
     [137]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            260.77 MiB (273438222 Bytes)
     # download with: lux -f 137 ...

0 B / 260.77 MiB [-------------------------------------------------------------------------------------------------------------------------------] ? p/s 0.00% ?Downloading https://www.youtube.com/watch?v=yE5Tpp2BSGw error:
https://rr1---sn-u5a3u5a3-h5oez.googlevideo.com/videoplayback?bui=AXc671KncqAVCTyAa6fPlQSOmxpgdvXdpM0xKgnocwrBRNgDUkpA3_SeFn9Hu-OqOTdJF5_w8toMS7CK&c=WEB&clen=45977005&dur=2840.868&ei=E1iJZpHRCpjDmLAP_-GIwAE&expire=1720298611&fvip=4&gir=yes&id=o-AJiTezBHJtmmore1S3mzHuqbuYHMzv33jdYxgj4Q9_L6&initcwndbps=1560000&ip=92.7.81.47&itag=140&keepalive=yes&lmt=1704424075521713&lsig=AHlkHjAwRQIgSNx-h2uSgz0R6jZWmPr9pzun-SruuLhnVZI572X0G34CIQCMFOZMh6KwAUw86dIGKYu1DdPWxG3VHVK4IikneHE08Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=65&mime=audio%2Fmp4&mm=31%2C29&mn=sn-u5a3u5a3-h5oez%2Csn-aigzrn7l&ms=au%2Crdu&mt=1720276649&mv=m&mvi=1&n=Y0WvKxUu-uRigZocFJX&ns=D9lwiy_keIn2zyHJPHQosgYQ&pl=20&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRQIgWxM19XavNqvEoOdcx6PMQvxY350txkoC8PqfCyK9IFcCIQCjCkwFtNZaJBotExQDTiqarMNGbHrtkYf_6P4IvSmUWA%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=NO7bAc6bmgXDK2TAuaPS6mzo0e2IFnrA7MHh0AdLI2Pfs0X_gBtluw72g8sW&svpuc=1&txp=5432434&vprv=1&xpc=EgVo2aDSNQ%3D%3D request error: HTTP 403
github.com/iawia002/lux/request.Request
	github.com/iawia002/lux/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
	github.com/iawia002/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
	github.com/iawia002/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
	github.com/iawia002/lux/downloader/downloader.go:675
runtime.goexit
	runtime/asm_amd64.s:1695
github.com/iawia002/lux/request.Request
	github.com/iawia002/lux/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
	github.com/iawia002/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
	github.com/iawia002/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
	github.com/iawia002/lux/downloader/downloader.go:675
runtime.goexit
	runtime/asm_amd64.s:1695
%
```

### Fixed version

```
% ~/go/bin/lux "https://www.youtube.com/watch?v=yE5Tpp2BSGw"

 Site:      YouTube youtube.com
 Title:     19. Rob Pike - What We Got Right, What We Got Wrong | GopherConAU 2023
 Type:      video
 Stream:
     [137]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            260.77 MiB (273438222 Bytes)
     # download with: lux -f 137 ...

260.77 MiB / 260.77 MiB [===========================================================================================================] 2.36 MiB p/s 100.00% 1m51s
Merging video parts into 19. Rob Pike - What We Got Right, What We Got Wrong - GopherConAU 2023.mp4
%
```

### CODE REVIEW

**Comment by Ada-lave** [comment]
Yep, i update and this works, thanks you

**Review by iawia002 — APPROVED** [review]
LGTM, thanks!

**Comment by cooloola** [comment]
> Yep, i update and this works, thanks you

How did you upgrade?

**Comment by SamBecca16** [comment]
how can I upgrade?

**Comment by gouarfig** [comment]
You can upgrade by compiling from source.

This is not actually complicated

1. you need to install the go toolkit at https://go.dev/dl/
2. then just run this command: `go install github.com/iawia002/lux@latest` and the new binary will be installed in your home directory at `go/bin`

**Comment by Lao-Shen** [comment]
After go install github.com/iawia002/lux@latest, the same error still occurs

```
$ HTTPS_PROXY="http://127.0.0.1:10809" lux "https://www.youtube.com/shorts/f_-AhpYJh_k"

 Site:      YouTube youtube.com
 Title:     Gotta reload to keep shooting [Compilation PART 64]
 Type:      video
 Stream:
     [299]  -------------------
     Quality:         1080p60 video/mp4; codecs="avc1.64002a"
     Size:            11.37 MiB (11921906 Bytes)
     # download with: lux -f 299 ...

0 B / 11.37 MiB [-----------------------------------------------------------------------------------------------------------------------] ? p/s 0.00% ?Downloading https://www.youtube.com/shorts/f_-AhpYJh_k error:
https://rr1---sn-a5mekndz.googlevideo.com/videoplayback?bui=AQmm2exYhJqkGEoP6LG9aPWFAD5Z_JyQH68sWiKmzq-XoRvHVlKKTG8XRrd2QVs62HomfkQzlKmjuykp&c=WEB&clen=269768&dur=16.602&ei=ex3QZuC7MMPisfIPvoC60AY&expire=1724936667&fvip=5&gir=yes&id=o-AF1YnLHz5kcZeGzcYrX3GCrY81RDMxMWaAT7jFZHhb0E&initcwndbps=1352500&ip=148.135.126.196&itag=140&keepalive=yes&lmt=1713002471207685&lsig=AGtxev0wRQIhAP_hAZD_H3TDhiK2dW168slmWlslh7ke13sOHUYXFbkPAiAzd4XbVaCfMlvykVnw_tAvvQYXo-v1ncxg0LyuZhyeWg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=om&mime=audio%2Fmp4&mm=31%2C29&mn=sn-a5mekndz%2Csn-a5msenes&ms=au%2Crdu&mt=1724914637&mv=m&mvi=1&n=YtjixpWn8sLHytRzuK&ns=84AOnr0_vAv5YMuIDSuoIUsQ&pl=17&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRgIhALlVxS_6xIxMjT4gd6a3jTrAXYPoIlhE718MXikgwwirAiEArsAUWyjTiC9fX9vq1d1FZG2MmMRqwMJJFzOL2Io184w%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=Mv1m9p6f64JyspQfHEgHQDsrG9O4VQfUYzdToKG-iTcTp5xvOQ8fhJ57hkFY&svpuc=1&txp=5532434&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=drc%3D1 request error: HTTP 403
github.com/iawia002/lux/request.Request
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:1695
github.com/iawia002/lux/request.Request
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:1695


```

**Comment by qinkangwu** [comment]
@Lao-Shen same error

**Comment by PRO-2684** [comment]
For anyone who don't want to compile, you can visit the `Actions` panel and download latest ci from `Builder` workflow.

**Comment by Spring2022abcjk** [comment]
i use the `go install github.com/iawia002/lux@latest` but the same error(403)

` Site:      YouTube youtube.com
 Title:     [Driver's View] Splashes of Colour on the Azalea-CL
 Type:      video
 Stream:
     [299]  -------------------
     Quality:         1080p60 video/mp4; codecs="avc1.64002a"
     Size:            694.01 MiB (727720579 Bytes)
     # download with: lux -f 299 ...

0 B / 694.01 MiB [--------------------------------------------------------------------------------------] ? p/s 0.00% ?Downloading https://youtu.be/v2Ffr3eU5lg?si=L5XUJ7Oqj7KIazWv error:
https://rr3---sn-i3b7knzl.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315&bui=AXLXGFRoM3tmjAPEk29Wjpd_G6Te8z0N9LLywj9UYAjJ3EU5oOOBQL6DV9f35DcK7pLOk2QRy8BTFvpz&c=WEB&clen=708857438&dur=1165.466&ei=v5sGZ-juDYuy2roPr872qQM&expire=1728507935&fexp=51300760&fvip=2&gir=yes&id=o-AH77Vx7qjufAbR3wCh_pLnfJFkQGHIu5YnwTGEH-TLBE&initcwndbps=1608750&ip=103.151.172.24&itag=299&keepalive=yes&lmt=1726367821323969&lsig=ACJ0pHgwRgIhAISOVQm-NgaSKrTEf1D3ITw8oXFXd0cyxYMcO1iCDXPHAiEAkkKEcnQwFhSk96NMTHCF49LFIMUS-1qoFzgwAV5wFSU%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&met=1728486335%2C&mh=bT&mime=video%2Fmp4&mm=31%2C26&mn=sn-i3b7knzl%2Csn-un57enez&ms=au%2Conr&mt=1728485834&mv=m&mvi=3&n=C8hSd1H67ngIBIrfI&ns=ihS1vlfL4LqGlpsZq2aihiIQ&pl=24&requiressl=yes&rms=au%2Cau&rqh=1&sefc=1&sig=AJfQdSswRQIhAMKcadgBHASsSE6kFToIzb8Lb2M_vN-NlHei0MaXYezLAiAOEfsLWJ4ExrTtqq65Oh_qUddVJjAg3OCbixSu35FM9A%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=54MbxfMb6dJS5uHD5-PR83J4rZIflp9O_M_q8NGKKYi8ZoVnKjkcypI-4Q&svpuc=1&txp=6309224&vprv=1&xpc=EgVo2aDSNQ%3D%3D request error: HTTP 403
github.com/iawia002/lux/request.Request
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1700
github.com/iawia002/lux/request.Request
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/petal/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1700
`

**Pull request merged**
